version: '3'
services:
  springboot-docker-compose-app-container:
    image: srjavcontainers.azurecr.io/spring-repo:latest
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/springboot-docker-compose-app
    ports:
      - "8080:8080"
