version: '3'
services:
  springboot-docker-compose-app-container:
    image: srjavcontainers.azurecr.io/spring-repo:95
    volumes:
      - /data/springboot-docker-compose-app
    ports:
      - "8080:8080"
